### ISSUE TITLE
Define GitOps scope

### ISSUE THREAD

**Issue by laurivosandi** [passmower/passmower#43]
I am starting to believe correct way to separate upstream IdP(s) managed attributes is by having separate Kubernetes subresources for them. 

```
apiVersion: codemowers.io/v1alpha1
kind: OIDCGWUser
metadata:
  name: johnsmith
status:
  emails:
    - johnsmith@gmail.com
    - johnsmith@example.com
  groups:
    - example.com:employees
    - github.com:example:admins
spec:
  type: person
  email: johnsmith@example.com
  groups:
    - employees
  displayName: John Smith
github:
  id: 12345
  emails:
    - email: johnsmith@gmail.com
      primary: true
slack:
  id: 12345
discord:
  id: 23456
foobar:
  sub: username-in-generic-upstream-oauth2-provider
```

The `spec` would be the source of truth for any local information and that one could be managed GitOps style. The `status` section would contain all data merged in sensible manner. Upstream provider(s) each have separate subresource for them so `kubectl apply` doesn't mangle that data.
